### ISSUE TITLE
No git tags?

### ISSUE THREAD

**Issue by kloczek** [OPENDAP/libdap#3]
On https://www.opendap.org/pub/source/ is possible to fined several version. Hovever in git there is not any tags marking code state on exact version.

**Comment by ndp-opendap** [comment]
The landing page for the current release of the server is here:

https://www.opendap.org/software/hyrax/1.16

Each component has its own releases in Git:

https://github.com/OPENDAP/olfs/releases
https://github.com/OPENDAP/bes/releases
https://github.com/OPENDAP/libdap4/releases

And the release version numbers correspond with the file names on:

https://www.opendap.org/pub/source/

**Comment by kloczek** [comment]
None of above repos are about libdap.

**This** repo (libdap) has no git tags at all.

**Comment by ndp-opendap** [comment]
Yes, and I am now noticing that this repo has not been used in more than 5 years. I didn't spot that on your first message. We have moved to the libdap4 repo. Try that and hopefully things will be more to your liking there.

**Comment by kloczek** [comment]
So maybe it would be good to rename it to libdap-outdatedand rename libdap4 to to libdap to not confuse people?
