### ISSUE TITLE
3.20.10 fails to build on i686 Fedora Rawhide

### ISSUE THREAD

**Issue by opoplawski** [OPENDAP/libdap#5]
Trying to update libdap to 3.20.10 in Fedora rawhide - build fails on i686 with:
```
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -I./gl -I./gl -I./GNU -I/usr/include/libxml2  -I/usr/include/tirpc    -Wall -W -Wcast-align -Wno-deprecated-register  -g -O2 --std=c++11  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c -o libdapclient_la-HTTPCache.lo `test -f 'HTTPCache.cc' || echo './'`HTTPCache.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./gl -I./gl -I./GNU -I/usr/include/libxml2 -I/usr/include/tirpc -Wall -W -Wcast-align -Wno-deprecated-register -g -O2 --std=c++11 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c HTTPCache.cc  -fPIC -DPIC -o .libs/libdapclient_la-HTTPCache.o
make[2]: Leaving directory '/builddir/build/BUILD/libdap-3.20.10'
In file included from HTTPCache.cc:53:
HTTPCacheInterruptHandler.h: In member function 'virtual void libdap::HTTPCacheInterruptHandler::handle_signal(int)':
HTTPCacheInterruptHandler.h:77:36: warning: unused parameter 'signum' [-Wunused-parameter]
   77 |     virtual void handle_signal(int signum)
      |                                ~~~~^~~~~~
HTTPCache.cc: In member function 'void libdap::HTTPCache::read_metadata(const std::string&, std::vector<std::__cxx11::basic_string<char> >&)':
HTTPCache.cc:1034:17: error: no matching function for call to 'min(const long unsigned int&, size_t)'
 1034 |         line[min(line_buf_len, strnlen(line, line_buf_len))-1] = '\0'; // erase newline
      |              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/12/string:50,
                 from /usr/include/c++/12/bits/locale_classes.h:40,
                 from /usr/include/c++/12/bits/ios_base.h:41,
                 from /usr/include/c++/12/ios:42,
                 from /usr/include/c++/12/ostream:38,
                 from /usr/include/c++/12/iostream:39,
                 from HTTPCache.cc:41:
/usr/include/c++/12/bits/stl_algobase.h:230:5: note: candidate: 'template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)'
  230 |     min(const _Tp& __a, const _Tp& __b)
      |     ^~~
/usr/include/c++/12/bits/stl_algobase.h:230:5: note:   template argument deduction/substitution failed:
HTTPCache.cc:1034:17: note:   deduced conflicting types for parameter 'const _Tp' ('long unsigned int' and 'size_t' {aka 'unsigned int'})
 1034 |         line[min(line_buf_len, strnlen(line, line_buf_len))-1] = '\0'; // erase newline
      |              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/12/bits/stl_algobase.h:278:5: note: candidate: 'template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)'
  278 |     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
/usr/include/c++/12/bits/stl_algobase.h:278:5: note:   template argument deduction/substitution failed:
HTTPCache.cc:1034:17: note:   deduced conflicting types for parameter 'const _Tp' ('long unsigned int' and 'size_t' {aka 'unsigned int'})
 1034 |         line[min(line_buf_len, strnlen(line, line_buf_len))-1] = '\0'; // erase newline
      |              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/12/algorithm:61,
                 from HTTPCache.cc:43:
/usr/include/c++/12/bits/stl_algo.h:5726:5: note: candidate: 'template<class _Tp> _Tp std::min(initializer_list<_Tp>)'
 5726 |     min(initializer_list<_Tp> __l)
      |     ^~~
/usr/include/c++/12/bits/stl_algo.h:5726:5: note:   template argument deduction/substitution failed:
HTTPCache.cc:1034:17: note:   mismatched types 'std::initializer_list<_Tp>' and 'long unsigned int'
 1034 |         line[min(line_buf_len, strnlen(line, line_buf_len))-1] = '\0'; // erase newline
      |              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/12/bits/stl_algo.h:5736:5: note: candidate: 'template<class _Tp, class _Compare> _Tp std::min(initializer_list<_Tp>, _Compare)'
 5736 |     min(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
/usr/include/c++/12/bits/stl_algo.h:5736:5: note:   template argument deduction/substitution failed:
HTTPCache.cc:1034:17: note:   mismatched types 'std::initializer_list<_Tp>' and 'long unsigned int'
 1034 |         line[min(line_buf_len, strnlen(line, line_buf_len))-1] = '\0'; // erase newline
      |              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HTTPCache.cc: At global scope:
HTTPCache.cc:1299:20: warning: 'template<class _Arg1, class _Arg2, class _Result> struct std::binary_function' is deprecated [-Wdeprecated-declarations]
 1299 | struct HeaderLess: binary_function<const string&, const string&, bool>
      |                    ^~~~~~~~~~~~~~~
In file included from /usr/include/c++/12/string:48:
/usr/include/c++/12/bits/stl_function.h:131:12: note: declared here
  131 |     struct binary_function
      |            ^~~~~~~~~~~~~~~
cc1plus: note: unrecognized command-line option '-Wno-deprecated-register' may have been intended to silence earlier diagnostics
make[2]: *** [Makefile:2279: libdapclient_la-HTTPCache.lo] Error 1
```

**Comment by ndp-opendap** [comment]
Hi Orion,

I think I have a patch for this. 

It's on GitHub branch "post_release_blues", pr: https://github.com/OPENDAP/libdap4/pull/192

I think the problem was the type difference in the call to std::min(). I made the first parameter in the invocation a size_t to match the value returned by strnlen() in the second parameter. 

If you could check and see if this is a fix I would greatly appreciate it.

Thanks,

Nathan


> On Jul 8, 2022, at 6:47 AM, Orion Poplawski ***@***.***> wrote:
> 
> 
> Trying to update libdap to 3.20.10 in Fedora rawhide - build fails on i686 with:
> 
> /bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -I./gl -I./gl -I./GNU -I/usr/include/libxml2  -I/usr/include/tirpc    -Wall -W -Wcast-align -Wno-deprecated-register  -g -O2 --std=c++11  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c -o libdapclient_la-HTTPCache.lo `test -f 'HTTPCache.cc' || echo './'`HTTPCache.cc
> libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./gl -I./gl -I./GNU -I/usr/include/libxml2 -I/usr/include/tirpc -Wall -W -Wcast-align -Wno-deprecated-register -g -O2 --std=c++11 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c HTTPCache.cc  -fPIC -DPIC -o .libs/libdapclient_la-HTTPCache.o
> make[2]: Leaving directory '/builddir/build/BUILD/libdap-3.20.10'
> In file included from HTTPCache.cc:53:
> HTTPCacheInterruptHandler.h: In member function 'virtual void libdap::HTTPCacheInterruptHandler::handle_signal(int)':
> HTTPCacheInterruptHandler.h:77:36: warning: unused parameter 'signum' [-Wunused-parameter]
>    77 |     virtual void handle_signal(int signum)
>       |                                ~~~~^~~~~~
> HTTPCache.cc: In member function 'void libdap::HTTPCache::read_metadata(const std::string&, std::vector<std::__cxx11::basic_string<char> >&)':
> HTTPCache.cc:1034:17: error: no matching function for call to 'min(const long unsigned int&, size_t)'
>  1034 |         line[min(line_buf_len, strnlen(line, line_buf_len))-1] = '\0'; // erase newline
>       |              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/12/string:50,
>                  from /usr/include/c++/12/bits/locale_classes.h:40,
>                  from /usr/include/c++/12/bits/ios_base.h:41,
>                  from /usr/include/c++/12/ios:42,
>                  from /usr/include/c++/12/ostream:38,
>                  from /usr/include/c++/12/iostream:39,
>                  from HTTPCache.cc:41:
> /usr/include/c++/12/bits/stl_algobase.h:230:5: note: candidate: 'template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)'
>   230 |     min(const _Tp& __a, const _Tp& __b)
>       |     ^~~
> /usr/include/c++/12/bits/stl_algobase.h:230:5: note:   template argument deduction/substitution failed:
> HTTPCache.cc:1034:17: note:   deduced conflicting types for parameter 'const _Tp' ('long unsigned int' and 'size_t' {aka 'unsigned int'})
>  1034 |         line[min(line_buf_len, strnlen(line, line_buf_len))-1] = '\0'; // erase newline
>       |              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /usr/include/c++/12/bits/stl_algobase.h:278:5: note: candidate: 'template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)'
>   278 |     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
>       |     ^~~
> /usr/include/c++/12/bits/stl_algobase.h:278:5: note:   template argument deduction/substitution failed:
> HTTPCache.cc:1034:17: note:   deduced conflicting types for parameter 'const _Tp' ('long unsigned int' and 'size_t' {aka 'unsigned int'})
>  1034 |         line[min(line_buf_len, strnlen(line, line_buf_len))-1] = '\0'; // erase newline
>       |              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/12/algorithm:61,
>                  from HTTPCache.cc:43:
> /usr/include/c++/12/bits/stl_algo.h:5726:5: note: candidate: 'template<class _Tp> _Tp std::min(initializer_list<_Tp>)'
>  5726 |     min(initializer_list<_Tp> __l)
>       |     ^~~
> /usr/include/c++/12/bits/stl_algo.h:5726:5: note:   template argument deduction/substitution failed:
> HTTPCache.cc:1034:17: note:   mismatched types 'std::initializer_list<_Tp>' and 'long unsigned int'
>  1034 |         line[min(line_buf_len, strnlen(line, line_buf_len))-1] = '\0'; // erase newline
>       |              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /usr/include/c++/12/bits/stl_algo.h:5736:5: note: candidate: 'template<class _Tp, class _Compare> _Tp std::min(initializer_list<_Tp>, _Compare)'
>  5736 |     min(initializer_list<_Tp> __l, _Compare __comp)
>       |     ^~~
> /usr/include/c++/12/bits/stl_algo.h:5736:5: note:   template argument deduction/substitution failed:
> HTTPCache.cc:1034:17: note:   mismatched types 'std::initializer_list<_Tp>' and 'long unsigned int'
>  1034 |         line[min(line_buf_len, strnlen(line, line_buf_len))-1] = '\0'; // erase newline
>       |              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> HTTPCache.cc: At global scope:
> HTTPCache.cc:1299:20: warning: 'template<class _Arg1, class _Arg2, class _Result> struct std::binary_function' is deprecated [-Wdeprecated-declarations]
>  1299 | struct HeaderLess: binary_function<const string&, const string&, bool>
>       |                    ^~~~~~~~~~~~~~~
> In file included from /usr/include/c++/12/string:48:
> /usr/include/c++/12/bits/stl_function.h:131:12: note: declared here
>   131 |     struct binary_function
>       |            ^~~~~~~~~~~~~~~
> cc1plus: note: unrecognized command-line option '-Wno-deprecated-register' may have been intended to silence earlier diagnostics
> make[2]: *** [Makefile:2279: libdapclient_la-HTTPCache.lo] Error 1
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

= = =
Nathan Potter                        ndp at opendap.org
OPeNDAP, Inc.                        +1.541.231.3317
